### PR TITLE
Contact form validation added to the project

### PR DESCRIPTION
**Pull request by fernando-silvabr66**
I´ve had some problems with another PR (which is closed in this same repo) so a made a new pull to my local repo and redid a sync in order to continue.

In this PR: Added contact form validation to the project.

### CODE REVIEW

**Review by t-yanick — APPROVED** [review]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by fernando-silvabr66** [comment]
Activity complete... cheers!!!✨🙌🎉

**Comment by fernando-silvabr66** [comment]
Activity complete... cheers!!!✨🙌🎉

**Comment by fernando-silvabr66** [comment]
Activity complete... cheers!!!✨🙌🎉

**Pull request merged**
